# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f012fca7334c24e2b7c15654074b16ba50b39d430581beb3f8766191e99261939f223e48770a0a030a20304acd192a24c7137f4dc915d2653b8a92f0bc7acb3

test:
  secret_key_base: ba63f6b692a14a3eacd510d0de305af7d7750e38ed93888345371a37106408de19b8729519d75ad53f056a1f76877045474b58ca0dc267a012b7060c8b5c85ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
